### ISSUE TITLE
Documentation input files

### ISSUE THREAD

**Issue by Saremox** [RSE-Cambridge/ISC17-SCC-miniDFT#3]
Where can I find documentation regarding the input files? 

Would like to reduce runtime of the provided small.in file for automatic CI testing of the code changes, we'll make. Current unoptimized runtime is over 5 min on a cluster node and a CI node have only limited hardware resources. Those runs are just used to automatically test the correctness of our code not for benchmarking.

**Comment by fspiga** [comment]
Hello Michael, the "small.in" test is already the minimum possible. In fact it does a single SCF iteration (see "electron_maxstep = 1").
